### ISSUE TITLE
patch_hf issue

### ISSUE THREAD

**Issue by 5taku** [em-llm/EM-LLM-model#1]
Hello. Thank you for the excellent paper idea and code.
I have attempted to reproduce the code exactly as provided.

model : Llama-3.1-8B-Instruct

config setting 

```
 {
            "name": "Python: CUDA Benchmark Debug",
            "type": "debugpy",
            "request": "launch",
            "program": "EM-LLM-model-main/benchmark/pred.py",
            "args": [
                "--config_path", "EM-LLM-model-main/config/llama31.yaml",
                "--output_dir_path", "EM-LLM-model-main/benchmark/results/llama31/infinite-bench",
                "--datasets", "'passkey'",
                "--world_size", "1",
                "--rank", "1",
                "--allow_disk_offload", "false"
            ],
            "console": "integratedTerminal",
            "env": {
                "CUDA_VISIBLE_DEVICES": "1"
            },
            "justMyCode": false
        }

```

After that, I encountered the following error:

```
 File "venv/em_llm/lib/python3.10/site-packages/transformers/models/llama/configuration_llama.py", line 161, in __init__
    self._rope_scaling_validation()
  File "venv/em_llm/lib/python3.10/site-packages/transformers/models/llama/configuration_llama.py", line 182, in _rope_scaling_validation
    raise ValueError(
ValueError: `rope_scaling` must be a dictionary with two fields, `type` and `factor`, got {'factor': 8.0, 'low_freq_factor': 1.0, 'high_freq_factor': 4.0, 'original_max_position_embeddings': 8192, 'rope_type': 'llama3'}
```

transformers version 4.41.0 ( requirements.txt -> transformers>=4.37.2,<=4.41.0 )

After searching for solutions, I found that upgrading the transformers version could resolve this issue, so I upgraded the transformers library.

```
Successfully installed tokenizers-0.21.1 transformers-4.51.2
```

When I ran it again, an error occurred at line 245 of patch_hf.py, stating that it could not find 'hf_rope = model.model.layers.self_attn.rotary_emb

In reality, the layer only contained qkv and o proj Linear modules.

After further research, I found a potential solution by downgrading to transformers 4.43.0, so I downgraded to this version.
After that, I found that (rotary_emb): LlamaRotaryEmbedding() existed, but the following code 'hf_rope.base = hf_rope.rope_kwargs.get("base", None).rope_theta' produced an AttributeError: 'NoneType' object has no attribute 'rope_theta'.

Could you provide guidance on how to resolve this issue?

**Comment by 5taku** [comment]
I try to 

hf_rope.base = 500000

it working. 

transformers 4.43.0

**Comment by MartinBenfeghoul** [comment]
Apologies for the late reply. As you have correctly identified, this is indeed linked to the version of the transformers library used. The downside of having a flexible multi-model patch of HuggingFace models means that the patch is sensitive to changes in this library, especially the handling of RoPE embeddings. Your last comment seems to suggest it is now working with version 4.43.0?

**Comment by Mrxiangli** [comment]
transformers 4.43.0 does not work.
